FROM postgres:latest

ENV POSTGRES_HOST_AUTH_METHOD=trust

# build with "docker build --tag postgresql_custom ."
# run using "docker run --rm -dit -p 5432:5432 --name postgresql_custom postgresql_custom"
# then connect with if using from WSL "psql -h localhost -p 5432 -U postgres"